### ISSUE TITLE
Use Node Allocatable Resources instead of raw Node Capacity

### ISSUE THREAD

**Issue by hjacobs** [hjacobs/kube-aws-autoscaler#11]
https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md

**Comment by hjacobs** [comment]
Hmm, in our Zalando AWS setup the values are currently identical:

```
kubectl get nodes ip-172-31-1-1.eu-central-1.compute.internal -o yaml
...
 allocatable:
    alpha.kubernetes.io/nvidia-gpu: "0"
    cpu: "2"
    memory: 15661512Ki
    pods: "110"
  capacity:
    alpha.kubernetes.io/nvidia-gpu: "0"
    cpu: "2"
    memory: 15661512Ki
    pods: "110"
...
```
