### ISSUE TITLE
autoscaler always tries to manage the Master ASG

### ISSUE THREAD

**Issue by magnusboman** [hjacobs/kube-aws-autoscaler#30]
I deployed the auto scaler without `--include-master-nodes`, but it still tries to manage the master ASG

> 2017-06-05 03:24:17,137 WARNING: Desired capacity for ASG ASGMaster is 2, but exceeds max 1

Deployment used:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    application: kube-aws-autoscaler
    version: v0.9
  name: kube-aws-autoscaler
spec:
  replicas: 1
  selector:
    matchLabels:
      application: kube-aws-autoscaler
  template:
    metadata:
      labels:
        application: kube-aws-autoscaler
        version: v0.9
      annotations:
        # FIXME: using hardcoded IAM role
        iam.amazonaws.com/role: auto-scaler-role
    spec:
      containers:
      - name: autoscaler
        image: hjacobs/kube-aws-autoscaler:0.9
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 50Mi
```
